# Generated by Django 2.2.28 on 2024-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_psicologia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='rut_estudiante',
            new_name='estudiante',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='rut_psicologo',
            new_name='psicologo',
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
