# Generated by Django 2.2.28 on 2024-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_psicologia', '0002_auto_20240722_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
