# Generated by Django 2.2.28 on 2024-07-15 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_apoderado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('seccion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConducta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_apoderado.Apoderado')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_estudiante.Curso')),
                ('tipo_conducta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_estudiante.TipoConducta')),
            ],
        ),
    ]
