# Generated by Django 2.2.28 on 2024-07-22 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_estudiante', '0002_auto_20240715_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='tipo_conducta',
        ),
        migrations.CreateModel(
            name='DatosAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_estudiante.Estudiante')),
                ('tipo_conducta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='area_estudiante.TipoConducta')),
            ],
        ),
    ]
