# Generated by Django 2.2.28 on 2024-07-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_estudiante', '0003_auto_20240721_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosalumno',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
