# Generated by Django 2.2.28 on 2024-07-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area_estudiante', '0004_datosalumno_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosAlumno',
        ),
    ]
