# Generated by Django 2.2.28 on 2024-07-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('docente', 'Docente'), ('alumno', 'Alumno'), ('apoderado', 'Apoderado'), ('psicologo', 'Psicólogo')], default='alumno', max_length=20),
        ),
    ]
