# Generated by Django 2.2.28 on 2024-07-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240715_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('docente', 'Docente'), ('apoderado', 'Apoderado'), ('psicologo', 'Psicólogo')], default='administrador', max_length=20),
        ),
    ]
