# Generated by Django 2.2.28 on 2024-07-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_docente', '0002_auto_20240720_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
