# Generated by Django 2.2.28 on 2024-07-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_docente', '0004_datosalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosalumno',
            name='docente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='area_docente.Docente'),
        ),
    ]
